auth/urls.py
from django.urls import path, include
urlpatterns = [
    path('', include('registration.backends.default.urls'))
]

comments/urls.py

from django.urls import path
from .views import leave_comment

app_name = 'comment'

urlpatterns = [
    path('<int:pk>/comment', leave_comment, name='leave_comment')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('comments.urls')),
    path('', include('rating.urls')),
    path('', include('films.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/urls.py
from django.urls import path
from .views import *

app_name = 'films'

urlpatterns = [
    path('<int:pk>/save', save_view, name='save-film')
]

pages/urls.py
from django.urls import path
from .views import *

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('films/', FilmsPageView.as_view(), name='films'),
    path('cartoons/', CartoonPageView.as_view(), name='cartoon'),
    path('search/', SearchPageView.as_view(), name='search'),
    path('<int:pk>/watch/', film_watch, name='watch'),
    path('liked/', LikedFilmsView.as_view(), name='liked-films'),
    path('saved/', SavedView.as_view(), name='saved-films')
]

rating/urls.py

from django.urls import path
from .views import rating_view

app_name = 'rating'

urlpatterns = [
    path('<int:pk>/rate', rating_view, name='rate_view')
]

comments/models.py
from django.db import models
from django.contrib.auth import get_user_model
from films.models import FilmModel
from django.utils.translation import gettext_lazy as _

UserModel = get_user_model()


class CommentModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, verbose_name=_('user'))
    film = models.ForeignKey(FilmModel, on_delete=models.CASCADE, verbose_name=_('film'))
    comment = models.TextField(max_length=1000, verbose_name=_('comment'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

films/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import datetime
from django.contrib.auth import get_user_model
from config.helpers import UploadTo
from django.contrib.auth.forms import forms
UserModel = get_user_model()

m_type = (
    ("film", "film"),
    ("cartoon", "cartoon"),
)

f_age = (
    ("6+", "6+"),
    ("8+", "8+"),
    ("12+", "12+"),
    ("16+", "16+"),
    ("18+", "18+"),
)


class YearModel(models.Model):
    year = models.PositiveIntegerField(unique=True, default=int(datetime.now().year), verbose_name=_('year'))

    def __str__(self):
        return str(self.year)

    class Meta:
        verbose_name = 'year'
        verbose_name_plural = 'years'


class GenreModel(models.Model):
    name = models.CharField(max_length=25, verbose_name=_("name"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="created at")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "genre"
        verbose_name_plural = "genres"


class TagModel(models.Model):
    name = models.CharField(max_length=25, verbose_name=_("name"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "tag"
        verbose_name_plural = "tags"


class FilmModel(models.Model):
    name = models.CharField(max_length=30, verbose_name=_("name"))
    image = models.ImageField(upload_to=UploadTo('film-image'), verbose_name=_("image"))
    film_video = models.FileField(upload_to=UploadTo('film-video'), verbose_name=_("film video"))
    description = models.TextField(max_length=3000, verbose_name=_("description"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))
    genre = models.ManyToManyField(GenreModel, verbose_name=_("genre"))
    tag = models.ManyToManyField(TagModel, verbose_name=_("tag"))
    year = models.ForeignKey(YearModel, on_delete=models.CASCADE, null=True, verbose_name="year")
    movie_type = models.CharField(max_length=20, choices=m_type, default=1, verbose_name=_("movie type"))
    age = models.CharField(max_length=3, choices=f_age, verbose_name=_('age'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('film')
        verbose_name_plural = _('films')

class BannerModel(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('name'))
    banner_img = models.ImageField(upload_to=UploadTo('banners'), verbose_name=_('banner img'))
    film = models.ForeignKey(FilmModel, on_delete=models.PROTECT, verbose_name=_('film'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "banner"
        verbose_name_plural = "banners"


class SavedFilmsModel(models.Model):
    film = models.ForeignKey(FilmModel, on_delete=models.CASCADE, verbose_name=_('film'))
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, verbose_name=_('user'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return f'{self.film}'

    class Meta:
        verbose_name = 'saved film'
        verbose_name_plural = 'saved films'

films/forms.py
from django.forms import ModelForm
from .models import SavedFilmsModel


class SaveForm(ModelForm):
    class Meta:
        model = SavedFilmsModel
        fields = '__all__'
        exclude = ('user', 'film')

films/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, TemplateView
from .models import FilmModel, SavedFilmsModel
from .forms import SaveForm


def save_view(request, pk):
    film = get_object_or_404(FilmModel.objects.all().filter(id=pk))
    if request.method == 'POST':
        form = SaveForm(request.POST)
        if form.is_valid():
            user = request.user
            if SavedFilmsModel.objects.filter(user=user, film=film).exists():
                SavedFilmsModel.objects.filter(user=user, film=film).delete()
            else:
                SavedFilmsModel.objects.create(user=user, film=film)
    return redirect(request.GET.get('next', '/'))

templates/main/liked-films.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
    <!-- BODY START  -->
    <div class="container-fluid container-lg pb-5 mt-5">

        <div class="row">
            <div class="col-12">
                <h2 class="d-flex text-white justify-content-center">Films you liked</h2>
            </div>
        </div>
        <!-- FILM CARDS START -->
        <div class="row mb-5 px-4">
        {% if object_list %}
            {% for film in object_list %}
                <div class="col-3 col-lg-3 col-xl-2 mt-5">
                    <div class="film-cards position-relative my-4">
                        <div class="film-card-in-div d-none position-absolute w-100 h-100">
                        {% if request.user.is_authenticated %}
                               <form method="post" action="{% url 'films:save-film' pk=film.film.id %}?next={{ request.path }}">
                                        {% csrf_token %}
                                        <button class="border-0 film-card-img p-0 pt-3 position-absolute bg-transparent"
                                                href="#">
                                               {% if film.film|is_saved:request.user %}
                                                <img src="{% static 'img/saved-bookmark.png' %}" class="img-fluid" alt="">
                                                {% else %}
                                                <img src="{% static 'img/bookmark-icon-light.png' %}" class="img-fluid" alt="">
                                            {% endif %}
                                        </button>
                                    </form>
                            {% endif %}
                            <div class="film-d-in-div w-100 position-absolute">
                                <p class="m-0 mx-2 mb-1">{{ film.film.year }} : {{ film.film.movie_type }}</p>
                                <p class="m-0 mx-2">{% for genre in film.film.genre.all %}
                                    {{ genre|lower|capfirst }},
                                {% endfor %}</p>
                            </div>
                            <div class="px-2 py-1 position-absolute watch-card-button w-100">
                                <a href="{% url 'pages:watch' pk=film.film.id %}" class="btn btn-primary p-1 w-100">
                                    <p class="m-0">Watch</p>
                                </a>
                            </div>
                        </div>
                        <img src="{{ film.film.image.url }}" class="mb-1 h-100 w-100 img-fluid" alt="">
                        <a href="{% url 'pages:watch' pk=film.pk %}" class=" film-name">
                            <p class="ps-1">{% if film.film.name|length > 35 %}{{ film.film.name|lower|capfirst|slice:'35' }}...{% else %}{{ film.film.name|lower|capfirst }}{% endif %}</p>
                        </a>
                    </div>
                </div>
            {% endfor %}
            {% else %}
                <div class="col-12 d-flex justify-content-center">
                    <h3 class="text-white py-5 my-5">You didn't like any film yet.</h3>
                </div>
            {% endif %}
        </div>

            <!-- FILM CARDS END -->
            {% if page_obj.paginator.count >= 25 %}
                <div class="row pt-3">
                    <div class="col-12 d-flex justify-content-center">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination ">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                           aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    {% if page_obj.number == page %}
                                        <li class="page-item ms-1"><a class="page-link active"
                                                                      href="?page={{ page }}">{{ page }}</a></li>
                                    {% elif page > page_obj.number|add:-6 and page < page_obj.number|add:6 %}
                                        <li class="page-item ms-1"><a class="page-link"
                                                                      href="?page={{ page }}">{{ page }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item ms-1">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                           aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    <!-- BODY END -->
    {{ years.year }}
{% endblock %}

templates/main/search.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
    <!-- BODY START  -->
    <div class="container-fluid container-lg pb-5 mt-5">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 offset-md-1 offset-lg-2 ">
                <h1 class="text-white d-flex justify-content-center py-2">Look for anything</h1>
                <form class="d-flex mx-0 mx-lg-5 py-2 px-lg-0" action="{% url 'pages:search' %}">
                    <input class="form-control me-2" value="{{ request.GET.q }}" name="q" type="search"
                           placeholder="Search"
                           aria-label="Search">
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>
            </div>
        </div>
        <!-- FILM CARDS START -->
        <div class="row px-4 justify-content-xl-center">
            {% if object_list %}
                {% for film in object_list %}
                    <div class="col-3 col-lg-3 col-xl-2 mt-5">
                        <div class="film-cards position-relative my-3">
                            <div class="film-card-in-div d-none position-absolute w-100 h-100">
                            {% if request.user.is_authenticated %}
                            <form method="post" action="{% url 'films:save-film' pk=film.id %}?next={{ request.path }}">
                                        {% csrf_token %}
                                        <button class="border-0 film-card-img p-0 pt-3 position-absolute bg-transparent"
                                                href="#">
                                            {% if film|is_saved:request.user %}
                                                <img src="{% static 'img/saved-bookmark.png' %}" class="img-fluid" alt="">
                                                {% else %}
                                                <img src="{% static 'img/bookmark-icon-light.png' %}" class="img-fluid" alt="">
                                            {% endif %}
                                        </button>
                                    </form>
                            {% endif %}
                                <div class="film-d-in-div w-100 position-absolute">
                                    <p class="m-0 mx-2 mb-1">{{ film.year }} : {{ film.movie_type }}</p>
                                    <p class="m-0 mx-2">{% for genre in film.genre.all %}
                                        {{ genre|title }},
                                    {% endfor %}</p>
                                </div>
                                <div class="px-2 py-1 position-absolute watch-card-button w-100">
                                    <a href="{% url 'pages:watch' pk=film.id %}" class="btn btn-primary p-1 w-100">
                                        <p class="m-0">Watch</p>
                                    </a>
                                </div>
                            </div>
                            <img src="{{ film.image.url }}" class="mb-1 h-100 w-100 img-fluid" alt="">
                            <a href="{% url 'pages:watch' pk=film.id %}" class=" film-name">
                                <p class="ps-1">{% if film.name|length > 35 %}{{ film.name|lower|capfirst|slice:'35' }}...{% else %}{{ film.name|lower|capfirst }}{% endif %}</p>
                            </a>
                        </div>
                    </div>

                {% endfor %}
            {% else %}
                <div class="col-12 py-5 pb-5 mb-5">
                    <h3 class="text-white mx-auto d-flex justify-content-center py-5 my-5 ">Sorry there is no film named
                        '<span class="text-primary">{{ request.GET.q }}</span>'</h3>
                </div>

            {% endif %}
        </div>
        <!-- FILM CARDS END -->
        {% if page_obj.paginator.count >= 13 %}
            <div class="row mt-5 pt-5">
                <div class="col-12 col-lg-8 offset-lg-2 d-flex justify-content-center">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination ">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                       aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for page in paginator.page_range %}
                                {% if page_obj.number == page %}
                                    <li class="page-item ms-1"><a class="page-link active"
                                                                  href="?page={{ page }}">{{ page }}</a></li>
                                {% elif page > page_obj.number|add:-4 and page < page_obj.number|add:4 %}
                                    <li class="page-item ms-1"><a class="page-link"
                                                                  href="?page={{ page }}">{{ page }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item ms-1">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                       aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        {% endif %}
    </div>
    <!-- BODY END -->
{% endblock %}

templates/main/watch.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
    <!-- BODY START -->
    <div class="container-fluid container-lg px-5 px-lg-0 my-5 pb-5 ">
        <div class="row film-detail">
            <div class="col-12  p-5">
                <div class="d-flex justify-content-center">
                    <img src="{{ film.image.url }}" class="img-fluid" alt="">
                    <div class="film-d px-5 my-auto">
                        <p><span>Name :</span> {{ film.name|lower|capfirst }}</p>
                        <P><span>Year :</span> {{ film.year }}</P>
                        <p><span>Genre :</span> {% for i in film.genre.all %}{{ i|lower|capfirst }}, {% endfor %}</p>
                        <p><span>Tags :</span> {% for j in film.tag.all %}{{ j|lower|capfirst }}, {% endfor %}</p>
                        <p><span>Type :</span> {{ film.movie_type|capfirst }}</p>
                        <p><span>Age :</span> {{ film.age }}</p>
                    </div>
                </div>
            </div>
            <div class="px-5">
                <hr class="bg-primary pt-1 m-0">
            </div>
            <!-- DESCRIPTION START -->
            <div class="col-12 film-description mt-4">
                <p class="description d-flex justify-content-center">Description</p>
                {% if film.description|length > 700 %}
                    <p class="px-5 text-">{{ film.description|lower|capfirst|slice:':700' }}
                        <span id="dots">...</span><span id="more">
                        {{ film.description|lower|slice:'700:' }}</span>
                    </p>

                    <button onclick="myFunction()" id="myBtn" class="read-more-button border-0 w-100 py-3 my-1">&#9660;
                        Read
                        more &#9660;
                    </button>
                {% else %}
                    <p class="px-5 text-">{{ film.description|lower|capfirst }}
                    {{ film.description }}
                {% endif %}
            </div>
        </div>
        <!-- DESCRIPTION END -->
        <!-- VIDEO START -->
        <div class="row mt-3">
            <div class="col-12 py-3 px-0 px-lg-5">
                <video controls class="w-100 video p-0 m-0">
                    <source src="{{ film.film_video.url }}" type="video/mp4">
                </video>
                <div class="d-flex mt-2 justify-content-center rating gap-3 py-3">
                    <div class="d-flex my-auto">
                        <p class="text-white m-0"><span class="text-primary">{{ total_likes }}</span> : LIKES</p>
                    </div>
                    {% if request.user.is_authenticated %}
                        <form method="POST" action="{% url 'rating:rate_view' pk=film.id %}">
                            {% csrf_token %}
                            <button value="True" type="submit" name="is_liked" value="{{ film.id }}" class="btn p-0">
                                {% if liked %}
                                    <img src="{% static 'img/liked-icon.png' %}" class="img-fluid" alt="">
                                {% else %}
                                    <img src="{% static 'img/like.png' %}" class="img-fluid" alt="">
                                {% endif %}
                            </button>
                        </form>
                        <form method="POST" action="{% url 'films:save-film' pk=film.id %}?next={{ request.path }}">
                            {% csrf_token %}
                            <button type="submit" name="is_liked" class="btn p-0">
                                {% if film|is_saved:request.user %}
                                <img src="{% static 'img/bookmark-watch-icon-light.png' %}" alt="">
                                {% else %}
                                <img src="{% static 'img/bookmark-icon-light.png' %}" alt="">
                                {% endif %}
                            </button>
                        </form>
                        <form method="POST" action="{% url 'rating:rate_view' pk=film.id %}">
                            {% csrf_token %}
                            <button value="False" type="submit" name="is_liked" value="{{ film.id }}" class="btn p-0">
                                {% if disliked %}
                                    <img src="{% static 'img/disliked-icon.png' %}" alt="">
                                {% else %}
                                    <img src="{% static 'img/dislike.png' %}" alt="">
                                {% endif %}
                            </button>
                        </form>
                    {% else %}
                        <a class="btn btn-outline-primary" href="{% url 'auth_login' %}?next={{ request.path }}">Log in to rate</a>
                    {% endif %}
                    <div class="d-flex my-auto">
                        <p class=" m-0 text-white">DISLIKES : <span class="text-primary">{{ total_dislikes }}</span></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- VIDEO END -->

        <!-- RELATED FILMS START -->
        <div class="row mt-5 mx-1">
            <div class="col-12">
                <h2 class="text-white m-3">Related Films</h2>
                <div class="my-slickies my-3">
                    {% for related in related %}
                        <div class="slicks position-relative slick-div mx-2">
                            <div class="slicks-inner-div position-absolute w-100 d-none">
                                {% if request.user.is_authenticated %}
                                    <form method="post" action="{% url 'films:save-film' pk=related.id %}?next={{ request.path }}">
                                        {% csrf_token %}
                                        <button href=""
                                                class="border-0 p-0 pe-lg-2 pe-xxl-0 position-absolute save-button bg-transparent">
                                            {% if related|is_saved:request.user %}
                                                <img src="{% static 'img/saved-bookmark.png' %}" class="img-fluid" alt="">
                                                {% else %}
                                                <img src="{% static 'img/bookmark-icon-light.png' %}" class="img-fluid" alt="">
                                            {% endif %}
                                        </button>
                                    </form>
                                {% endif %}
                                <div class="position-absolute slicks-inner-content w-100">
                                    <div>
                                        <p class="m-0 ms-2 text-white">{{ related.year }} :</p>
                                        <p class="m-0 mb-3 ms-1 text-white">
                                            {% for genre in related.genre.all %}{{ genre }}, {% endfor %}</p>
                                    </div>
                                    <div class="px-2 py-1 watch-button position-absolute w-100">
                                        <a href="{% url 'pages:watch' pk=related.id %}" class="btn btn-primary p-1 w-100">
                                            <p class="m-0">Watch</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <img src="{{ related.image.url }}" class="slick-img w-100 h-100" alt="">
                            <a href="#">
                                <p class="text-white film-name mt-1 ms-1">{{ related.name|lower|capfirst }}</p>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- RELATED FILMS END -->
        <!-- COMMENTS START -->
        <div class="col-12 comments p-3">
            <p class="text-white d-flex justify-content-center description">Comments</p>
            <div class="px-3">
                <hr class="bg-primary pt-1 m-0">
            </div>
            <div class="w-100 mt-3 px-3 gap-3 d-flex flex-column">
                {% if comments %}
                    {% for comment in comments %}
                        <div class="p-3 comment">
                            <div class="d-flex">
                                <p class="text-white ms-2 my-auto">{{ comment.user }}
                                    : {{ comment.created_at|timesince }} ago</p>
                            </div>
                            <p class="text-white p-3 m-0">{{ comment.comment }}</p>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="comment">
                        <div class="d-flex justify-content-center">
                            <p class="text-white m-0 my-2   ">There's no any comment yet</p>
                        </div>
                    </div>

                {% endif %}
                {% if request.user.is_authenticated %}
                    <form id="comments" action="{% url 'comment:leave_comment' pk=film.id %}" method="post"
                          class="comment d-flex">
                        {% csrf_token %}
                        <input placeholder="Leave a comment" name="comment" maxlength="1000" required="" id="id_comment"
                               type="text"
                               class="comment-input w-100 p-2 bg-transparent">
                        <button type="submit" class="h-100 btn btn-outline-primary p-3">Submit</button>
                    </form>
                {% else %}
                    <div class="d-flex justify-content-center">
                        <a href="{% url 'auth_login' %}?next={{ request.path }}" class="btn btn-outline-primary">Log in to leave a comment</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <!-- COMMENTS END -->
    </div>
    <!-- BODY END -->
{% endblock %}