auth/urls.py
from django.urls import path, include
urlpatterns = [
    path('', include('registration.backends.default.urls'))
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('comments.urls')),
    path('', include('rating.urls')),
    path('', include('films.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import *

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('films/', FilmsPageView.as_view(), name='films'),
    path('cartoons/', CartoonPageView.as_view(), name='cartoon'),
    path('search/', SearchPageView.as_view(), name='search'),
    path('<int:pk>/watch/', film_watch, name='watch'),
    path('liked/', LikedFilmsView.as_view(), name='liked-films'),
    path('saved/', SavedView.as_view(), name='saved-films')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cinema.uz</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'slick-1.8.1/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'slick-1.8.1/slick/slick-theme.css' %}">
    <link rel="icon" href="{% static 'img/web-icon.svg' %}">
</head>

<body>
<!-- NAVBAR START -->
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid px-4">
        <a class="navbar-brand d-flex" href="{% url 'pages:home' %}">
            <img src="{% static 'img/icon.png' %}" class="brand-icon" alt="">
            <h4 class="my-auto ms-1 brand-name">Cinema.uz</h4>
        </a>
        <div class="d-flex flex-row">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown d-block d-lg-none">
                    <div class="dropstart">
                        <a class="nav-link text-white btn dropdown-toggle my-2" href="#"
                           id="navbarDarkDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username|title }}
                        </a>
                        <ul class="dropdown-menu mt-2 dropdown-menu-dark">
                            {% url 'pages:saved-films' as current_path %}
                            <li>
                                <a class="{% if request.path == current_path %} dropdown-active {% endif %} dropdown-item"
                                   href="{% url 'pages:saved-films' %}"><img alt=""
                                                                             class="nav-icon me-2"
                                                                             src="{% static 'img/bookmark-icon.png' %}">Saved
                                    films
                                </a>
                            </li>
                            {% url 'pages:liked-films' as current_path %}
                            <li><a class="{% if request.path == current_path %}dropdown-active{% endif %} dropdown-item"
                                   href="{% url 'pages:liked-films' %}"><img alt=""
                                                                             class="nav-icon me-2"
                                                                             src="{% static 'img/like-dark.png' %}">Liked
                                films
                            </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'auth_password_change' %}"><img alt=""
                                                                                                      class="nav-icon me-2"
                                                                                                      src="{% static 'img/change-password-icon.png' %}">Change
                            </a>
                            </li>
                            {% url 'pages:saved-films' as u1 %}
                            {% url 'pages:liked-films' as u2 %}
                            <li><a class="dropdown-item"
                                   href="{% url 'auth_logout' %}
                                    {% if request.path == u1 %}?next={% url 'pages:home' %}
                                    {% elif request.path == u2 %}?next={% url 'pages:home' %}
                                    {% else %}?next={{ request.path }}
                                    {% endif %}">
                                <img alt="" class="nav-icon me-2" src="{% static 'img/logout-icon.png' %}">Log out</a>
                            </li>
                            </li>
                        </ul>
                    </div>
                </li>
            {% else %}

                <li class="nav-item d-block d-lg-none py-1 me-3">
                    <a href="{% url 'auth_login' %}?next={{ request.path }}">
                        <button class="btn btn-outline-success">Log in</button>
                    </a>
                </li>
            {% endif %}

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex flex-lg-row flex-column align-items-center">
                {% url 'pages:home' as current_path %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == current_path %}active{% endif %}"
                       href="{% url 'pages:home' %}">Home</a>
                </li>
                {% url 'pages:films' as current_path %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == current_path %}active{% endif %}"
                       href="{% url 'pages:films' %}">Films</a>
                </li>
                {% url 'pages:cartoon' as current_path %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == current_path %}active{% endif %}"
                       href="{% url 'pages:cartoon' %}">Cartoons</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown d-none d-lg-block">
                    <div class="dropstart">
                        <button class="nav-link text-white btn dropdown-toggle my-2"
                           id="navbarDarkDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username|title }}
                        </button>
                        <ul class="dropdown-menu mt-2 dropdown-menu-dark">
                            {% url 'pages:saved-films' as current_path %}
                            <li>
                                <a class="{% if request.path == current_path %} dropdown-active {% endif %} dropdown-item"
                                   href="{% url 'pages:saved-films' %}"><img alt=""
                                                                             class="nav-icon me-2"
                                                                             src="{% static 'img/bookmark-icon.png' %}">Saved
                                    films
                                </a>
                            </li>
                            {% url 'pages:liked-films' as current_path %}
                            <li>
                                <a class="{% if request.path == current_path %} dropdown-active {% endif %} dropdown-item"
                                   href="{% url 'pages:liked-films' %}"><img alt=""
                                                                             class="nav-icon me-2"
                                                                             src="{% static 'img/like-dark.png' %}">Liked
                                    films
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'auth_password_change' %}"><img alt=""
                                                                                                      class="nav-icon me-2"
                                                                                                      src="{% static 'img/change-password-icon.png' %}">Change
                            </a>
                            </li>
                            {% url 'pages:saved-films' as u1 %}
                            {% url 'pages:liked-films' as u2 %}
                            <li><a class="dropdown-item"
                                   href="{% url 'auth_logout' %}{% if request.path == u1%}?next={% url 'pages:home' %}
                                    {% elif request.path == u2 %}?next={% url 'pages:home' %}
                                    {% else %}?next={{ request.path }}{% endif %}">
                                <img alt="" class="nav-icon me-2" src="{% static 'img/logout-icon.png' %}">Log out</a>
                            </li>
                        </ul>
                    </div>
                </li>
            {% else %}
                <li class="nav-item d-none d-lg-block py-2">
                    <a href="{% url 'auth_login' %}?next={{ request.path }}">
                        <button class="btn btn-outline-success">Log in</button>
                    </a>
                </li>
            {% endif %}
            {% url 'pages:search' as searching %}
            {% if request.path != searching %}
                <form class="d-flex mx-3 py-2 px-5 px-lg-0" action="{% url 'pages:search' %}">
                    <input class="form-control me-2" value="{{ request.GET.q }}" name="q" type="search"
                           placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>
            {% endif %}
        </div>
    </div>
</nav>
<!-- NAVBAR END -->

{% block content %}

{% endblock %}

<!-- FOOTER START -->
<div class="container-fluid container-lg px-5 px-lg-0 mt-5  p-0">
    <div class="row footer justify-content-between p-5">
        <div class="col-3 col-md-3 col-lg-4 ">
            <p class="d-flex justify-content-center">Contact Us</p>
            <hr>
            <div class="d-flex justify-content-center">
                <a href="https://www.instagram.com/master_2292">
                    <img class="contact-icons" src="{% static 'img/instagram-icon.png' %}" alt="">
                </a>
                <a href="https://www.facebook.com/" class="ms-3">
                    <img class="contact-icons" src="{% static 'img/facebook-icon.png' %}" alt="">
                </a>
                <a href="https://t.me/Master_2907" class="ms-3">
                    <img class="contact-icons" src="{% static 'img/telegram-icons.png' %}" alt="">
                </a>
                <a href="https://www.youtube.com/" class="ms-3">
                    <img class="contact-icons" src="{% static 'img/youtube.png' %}" alt="">
                </a>
            </div>
        </div>
        <div class="col-3 col-lg-4 d-flex flex-column">
            <p class="m-0 d-flex justify-content-center">Watch</p>
            <hr>
            <div class="d-flex justify-content-center flex-column align-items-center">
                <a href="{% url 'pages:home' %}" class="film-name">home</a>
                <a href="{% url 'pages:films' %}" class="film-name">films</a>
                <a href="{% url 'pages:cartoon' %}" class="film-name">cartoons</a>
            </div>
        </div>
        <div class="col-3 ">
            <h1 class="">Cinema.uz</h1>
            <h5 class="text-white mt-3">Watch any film for free !</h5>
        </div>
    </div>
</div>
<!-- FOOTER END -->

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'slick-1.8.1/slick/slick.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>
